# Generated by Django 4.2.7 on 2023-11-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='Task',
        ),
    ]
