# Generated by Django 4.2.7 on 2023-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_todo_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2001-12-4'),
            preserve_default=False,
        ),
    ]
